addons:
  apt:
    packages:
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libpng-dev
    - libxml-parser-perl
    - libxtst-dev
    - xutils-dev
    - libmount-dev
script:
- ./bootstrap.sh manifest.txt
- tar cJf deps.txz local
deploy:
  provider: releases
  api_key:
    secure: Bw7wOlzvEx1fsFMy5SAxDHodz4XxyBbscbAGMd4uneNY08hA1pIzHOLfe5HWYsYBknDTATpMVlHFp86rM7YML+S/S1bVd5Bwh37aPZ1fmlXWE0v1G4uN3NMNZAjU1oXrtn8D97LvCqe+NBK4i0lr44VbDaOKX33r3/aIZjAIroTFUp49rrsE9mIf3uUXojFqCxQIjEIUgJmO7yz6bDu7XmFgJePhCvdX/SMwYEycsN+FRgrZDQ7kakqdP+u4D/OYOlNN99ykLq2TegayPRA2X7td63xUY0O4E8kBx0g1L8nAgVK3j83l8y11lIT5gBpm4tyQH2wqB4ncZKgT/jfrFrE3XsEevfjzLEAxj1lu1AEXqWJ78yXB9KxPJ4dHJHRB7/8xa0YzXMkZV04JRsZXaPSwUQUVPRjkXlwiiT1xA3P5wyCotCEVuzsUwkCJPvsacOTDEhwaPu36qqJfYEhLLCk9qDwWZdgOZRnsWti6GmljT5VEthtqU3RHKT2zuNf75rTKp3XZJXLftocAjUrnR/9X1krx8N4fCdRbWxO000eS2gw1vXrQcVK8xb4CIbZ8n6qBosMiUdLsai8j+mSHwuwRbZEnRhqTCxFHHawzvhaA5/DkBKQtk1T4QyP49w+d4lF9KEFn23e5585Gza21FLRTBxHr8ar4OxAO2U+6vaM=
  file: deps.txz
  skip_cleanup: true
  on:
    tags: true
